config/routes.rb
Rails.application.routes.draw do
  resources :plants
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "plants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
	validates :email, :name, presence: true

	has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:email, :name)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :person_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Planter", root_path %></h1>
      <nav>
        <ul>
          <li><%= link_to "People", people_path %></li>
          <li><%= link_to "Plants", plants_path %></li>
        </ul>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.email %></td>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
	<strong>Plants:</strong>
	<ul>
		<% @person.plants.each do |plant| %>
		<li><%= link_to plant.name, plant_path(plant) %></li>
		<% end %>
	</ul>
</p>

<%= link_to 'New Plant', new_plant_path(person_id: @person.id) %> |
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.select :person_id, Person.all.collect { |p| [ p.name, p.id ] }, include_blank: 'Pick a Person', selected: params[:person_id]%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= link_to plant.person.name, person_path(plant.person) %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Person:</strong>
  <%= link_to @plant.person.name, person_path(@plant.person) %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>